// Code generated by stacker -type disk ; DO NOT EDIT

package main

type diskStack struct {
	data []disk
}

func (s *diskStack) Push(v disk) {
	s.data = append(s.data, v)
}

func (s *diskStack) Pop() (v disk, ok bool) {
	if len(s.data) == 0 {
		return v, false
	}
	top := len(s.data) - 1
	v = s.data[top]
	s.data = s.data[:top]
	return v, true
}

func (s *diskStack) Peek() (v disk, ok bool) {
	if len(s.data) == 0 {
		return v, false
	}
	top := len(s.data) - 1
	v = s.data[top]
	return v, true
}

func (s *diskStack) Len() int {
	return len(s.data)
}

func (s *diskStack) Walk(f func(disk)) {
	for _, v := range s.data {
		f(v)
	}
}

func (s *diskStack) Rotate() {
	if len(s.data) == 0 {
		return
	}

	top := len(s.data) - 1
	s.data = append(s.data[top:], s.data[:top]...)
}

func (s *diskStack) Unrotate() {
	if len(s.data) == 0 {
		return
	}

	bottom := 0
	s.data = append(s.data[bottom+1:], s.data[bottom])
}
